In [1]:
import tensorflow as tf
from preprocessing import PreProcessing
from model import TripletLoss
import keras

flags = tf.app.flags
FLAGS = flags.FLAGS
flags.DEFINE_integer('batch_size', 512, 'Batch size.')
flags.DEFINE_integer('train_iter', 1500, 'Total training iter')
flags.DEFINE_integer('step', 50, 'Save after ... iteration')
flags.DEFINE_float('learning_rate','0.01','Learning rate')
flags.DEFINE_float('momentum','0.99', 'Momentum')
flags.DEFINE_string('model', 'conv_net', 'model to run')
#flags.DEFINE_string('data_src', './data_repository/geological_similarity/', 'source of training dataset')
flags.DEFINE_string('data_src', './data_repository/Veri776/', 'source of training dataset')


c:\users\kuruparans\anaconda3\envs\imtf\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\kuruparans\anaconda3\envs\imtf\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\kuruparans\anaconda3\envs\imtf\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\kuruparans\anaconda3\envs\imtf\lib\site-packages\ten

In [2]:
import os
from matplotlib.image import imread
import numpy as np
from PIL import Image



from gms import GmsMatcher
from gms import Size
from gms import DrawingType
import math
from enum import Enum

import cv2
cv2.ocl.setUseOpenCL(False)

import numpy as np


In [3]:
dataset = PreProcessing('./data_repository/12/')


Loading Veri776 Dataset...
001
[[[123 130 127]
  [121 128 125]
  [121 127 124]
  ...
  [176 188 188]
  [179 191 191]
  [182 194 194]]

 [[121 128 125]
  [123 130 127]
  [126 133 130]
  ...
  [175 186 186]
  [178 190 190]
  [181 193 193]]

 [[119 126 123]
  [124 131 128]
  [129 136 133]
  ...
  [174 186 186]
  [178 190 190]
  [180 193 192]]

 ...

 [[111 117 116]
  [111 117 116]
  [111 116 116]
  ...
  [120 126 121]
  [121 127 122]
  [122 128 122]]

 [[112 118 117]
  [113 118 118]
  [112 118 117]
  ...
  [121 127 122]
  [122 128 123]
  [122 128 123]]

 [[113 119 118]
  [113 119 118]
  [114 120 119]
  ...
  [122 128 123]
  [122 128 123]
  [123 129 124]]]
[[[168 179 177]
  [169 180 178]
  [165 174 173]
  ...
  [127 135 134]
  [126 134 133]
  [126 134 133]]

 [[169 180 178]
  [167 178 176]
  [158 168 166]
  ...
  [127 135 134]
  [127 135 134]
  [127 135 134]]

 [[168 179 177]
  [163 174 172]
  [150 159 158]
  ...
  [127 135 134]
  [129 137 136]
  [132 140 139]]

 ...

 [[112 117 118]
  [11

  [118 116 116]]]
[[[133 128 129]
  [133 128 129]
  [133 128 129]
  ...
  [145 144 146]
  [145 144 146]
  [146 145 147]]

 [[133 128 129]
  [133 128 129]
  [133 128 129]
  ...
  [145 144 146]
  [146 145 147]
  [146 145 147]]

 [[134 129 130]
  [134 129 130]
  [134 129 130]
  ...
  [146 145 147]
  [146 145 147]
  [146 145 147]]

 ...

 [[127 127 127]
  [125 125 125]
  [123 123 123]
  ...
  [117 112 113]
  [117 114 114]
  [117 115 115]]

 [[126 125 125]
  [126 124 124]
  [125 124 124]
  ...
  [116 113 113]
  [116 114 114]
  [116 114 114]]

 [[126 124 124]
  [126 124 124]
  [126 124 124]
  ...
  [115 113 113]
  [116 113 113]
  [116 114 114]]]
[[[121 119 125]
  [121 119 125]
  [120 118 124]
  ...
  [ 83  78  79]
  [ 75  70  70]
  [ 72  67  66]]

 [[121 119 124]
  [120 118 124]
  [120 118 124]
  ...
  [ 85  80  80]
  [ 77  72  72]
  [ 74  69  68]]

 [[119 117 123]
  [119 117 123]
  [119 117 123]
  ...
  [ 93  88  88]
  [ 86  81  81]
  [ 84  79  78]]

 ...

 [[141 136 136]
  [142 136 136]
  

  [126 152 164]]]
[[[ 36  36  36]
  [ 23  23  23]
  [ 13  13  13]
  ...
  [110 115 114]
  [110 115 114]
  [110 115 114]]

 [[ 21  21  21]
  [ 15  15  15]
  [ 15  15  15]
  ...
  [110 115 114]
  [110 115 114]
  [110 115 114]]

 [[  3   3   3]
  [  7   7   7]
  [ 18  18  18]
  ...
  [110 115 114]
  [110 115 114]
  [110 115 114]]

 ...

 [[102 102 102]
  [101 101 101]
  [101 101 101]
  ...
  [ 32  41  60]
  [ 23  30  49]
  [ 36  43  62]]

 [[102 102 102]
  [101 101 101]
  [101 101 101]
  ...
  [ 17  25  43]
  [ 25  32  50]
  [ 45  51  69]]

 [[102 102 102]
  [101 101 101]
  [101 101 101]
  ...
  [  7  15  32]
  [ 26  34  51]
  [ 50  57  74]]]
[[[240 242 243]
  [213 215 216]
  [166 168 169]
  ...
  [108 113 112]
  [108 113 112]
  [108 113 112]]

 [[191 192 193]
  [166 168 169]
  [133 135 137]
  ...
  [108 113 112]
  [108 113 112]
  [108 113 112]]

 [[125 124 126]
  [103 105 106]
  [ 89  91  92]
  ...
  [108 113 112]
  [108 113 112]
  [108 113 112]]

 ...

 [[ 98  98  98]
  [ 98  98  98]
  

  [130 125 126]]]
[[[145 144 148]
  [145 144 148]
  [145 144 148]
  ...
  [154 149 150]
  [154 149 150]
  [153 148 149]]

 [[145 144 148]
  [145 144 148]
  [145 144 148]
  ...
  [154 149 150]
  [154 149 150]
  [154 149 150]]

 [[145 144 148]
  [145 144 148]
  [145 144 148]
  ...
  [153 148 149]
  [153 149 150]
  [154 149 150]]

 ...

 [[132 129 131]
  [131 129 130]
  [132 129 131]
  ...
  [123 118 119]
  [123 118 119]
  [124 119 120]]

 [[132 129 131]
  [132 129 131]
  [133 130 132]
  ...
  [124 119 120]
  [124 119 120]
  [125 120 121]]

 [[133 130 132]
  [133 130 132]
  [133 130 132]
  ...
  [125 120 121]
  [125 120 121]
  [125 120 121]]]
[[[153 148 149]
  [153 148 149]
  [153 148 149]
  ...
  [151 147 153]
  [151 147 153]
  [151 147 153]]

 [[153 148 149]
  [153 148 149]
  [153 148 149]
  ...
  [151 147 153]
  [151 147 153]
  [151 147 153]]

 [[153 148 149]
  [153 148 149]
  [153 148 149]
  ...
  [151 147 153]
  [151 147 153]
  [151 147 153]]

 ...

 [[133 131 131]
  [133 131 131]
  

[[[164 174 174]
  [164 174 174]
  [166 173 176]
  ...
  [158 156 156]
  [157 155 155]
  [157 155 155]]

 [[164 174 174]
  [164 174 174]
  [166 173 176]
  ...
  [156 154 154]
  [156 154 154]
  [156 154 154]]

 [[166 173 176]
  [166 173 176]
  [166 173 176]
  ...
  [156 154 154]
  [155 153 153]
  [155 153 153]]

 ...

 [[115 110 111]
  [113 108 109]
  [113 108 109]
  ...
  [120 117 119]
  [122 119 121]
  [125 122 124]]

 [[115 110 111]
  [114 109 110]
  [113 108 109]
  ...
  [120 117 119]
  [122 119 121]
  [125 122 124]]

 [[115 110 111]
  [114 109 110]
  [113 108 109]
  ...
  [120 117 119]
  [122 119 121]
  [125 122 124]]]
[[[169 175 186]
  [168 174 185]
  [169 174 185]
  ...
  [162 157 159]
  [161 156 158]
  [160 155 157]]

 [[169 175 186]
  [168 174 185]
  [169 173 184]
  ...
  [161 156 158]
  [161 156 158]
  [161 156 158]]

 [[167 176 186]
  [166 174 184]
  [166 172 183]
  ...
  [163 158 159]
  [161 156 158]
  [160 155 157]]

 ...

 [[125 120 121]
  [125 120 121]
  [121 116 117]
  ..

  [137 139 133]]]
[[[156 157 155]
  [156 157 155]
  [156 157 155]
  ...
  [156 162 152]
  [178 183 174]
  [210 215 206]]

 [[156 157 155]
  [156 157 155]
  [156 157 155]
  ...
  [152 159 148]
  [157 163 152]
  [166 170 161]]

 [[156 157 155]
  [156 157 155]
  [156 157 155]
  ...
  [159 165 154]
  [150 156 145]
  [136 141 132]]

 ...

 [[148 154 153]
  [148 154 153]
  [148 154 153]
  ...
  [133 139 138]
  [133 139 138]
  [134 140 139]]

 [[148 154 153]
  [148 154 153]
  [148 154 153]
  ...
  [133 139 138]
  [133 139 138]
  [134 140 139]]

 [[148 154 153]
  [148 154 153]
  [148 154 153]
  ...
  [133 139 138]
  [133 139 138]
  [134 140 139]]]
[[[151 155 150]
  [151 155 150]
  [150 154 149]
  ...
  [150 153 151]
  [151 154 152]
  [151 152 150]]

 [[151 155 150]
  [151 155 150]
  [151 155 150]
  ...
  [154 155 153]
  [154 154 152]
  [156 154 153]]

 [[150 155 150]
  [150 155 149]
  [150 156 149]
  ...
  [153 153 153]
  [155 154 154]
  [155 153 153]]

 ...

 [[143 151 150]
  [142 150 149]
  

Preprocessing Done. Summary:
Images train : (333, 224, 224, 3)
Labels train : (333,)
Images test  : (35, 224, 224, 3)
Labels test  : (35,)
Unique label : [0 1 2 3 4 5 6 7]


In [4]:
import os
from matplotlib.image import imread
import numpy as np
from PIL import Image


from gms import GmsMatcher
from gms import Size
from gms import DrawingType
import math
from enum import Enum

import cv2
cv2.ocl.setUseOpenCL(False)

import numpy as np


In [6]:
def computefeat(temp,direcX):
    feature = [[0 for i in range(len(temp))] for j in range(len(temp))] 

    for i in range(0,len(temp)):
        for j in range(0,len(temp)):
            img1 = (np.array(direcX[0][i]))
            img2 = (np.array(direcX[0][j]))

            if(i==j):
                continue

            if(i!=j):
                orb = cv2.ORB_create(10000)
                orb.setFastThreshold(0)
                if cv2.__version__.startswith('3'):
                    matcher = cv2.BFMatcher(cv2.NORM_HAMMING)
                else:
                    matcher = cv2.BFMatcher_create(cv2.NORM_HAMMING)
                gms = GmsMatcher(orb, matcher)

                matches = gms.compute_matches(img1, img2)
                #gms.draw_matches(img1, img2, DrawingType.ONLY_LINES)
                #gms.draw_matches(img1, img2, DrawingType.LINES_AND_POINTS)
                #print(len(matches))           
                feature[i][j]=len(matches)
    return feature

In [9]:
data_src= './data_repository/Veri776/'
X = []
y = []
direcX=[]
direcy=[]
F=[]
id=[]
for directory in os.listdir(data_src):
    print(directory)
    temp=[]
    c=0
    try:
        for pic in os.listdir(os.path.join(data_src, directory)):
            #img = imread(os.path.join(self.data_src, directory, pic))
            #img = Image.open(os.path.join(self.data_src, directory, pic))
            #img=img.resize((224,224))
            
            img = cv2.imread(os.path.join(data_src, directory, pic))
            img = cv2.resize(img, (224,224))
            #print(img)

            temp.append(np.squeeze(np.asarray(img)))
            
            X.append(np.squeeze(np.asarray(img)))
            y.append(directory)
            id.append(c)
            c=c+1
        direcX.append(np.array(temp))
        direcy.append(directory)
        F.append(np.squeeze(np.asarray(computefeat(temp,direcX))))
        #print(direcX)
    except Exception as e:
        print('Failed to read images from Directory: ', directory)
        print('Exception Message: ', e)
print('Dataset loaded successfully.')


001
002
Failed to read images from Directory:  002
Exception Message:  index 52 is out of bounds for axis 0 with size 52
003
004
005
Failed to read images from Directory:  005
Exception Message:  index 52 is out of bounds for axis 0 with size 52
006
Failed to read images from Directory:  006
Exception Message:  index 52 is out of bounds for axis 0 with size 52
007
008
009
Failed to read images from Directory:  009
Exception Message:  index 52 is out of bounds for axis 0 with size 52
010
011
012
013
Failed to read images from Directory:  013
Exception Message:  index 52 is out of bounds for axis 0 with size 52
014
015
Failed to read images from Directory:  015
Exception Message:  index 52 is out of bounds for axis 0 with size 52
016
Failed to read images from Directory:  016
Exception Message:  index 52 is out of bounds for axis 0 with size 52
017
Failed to read images from Directory:  017
Exception Message:  index 52 is out of bounds for axis 0 with size 52
018
Failed to read images fr

153
154
155
156
Failed to read images from Directory:  156
Exception Message:  index 52 is out of bounds for axis 0 with size 52
157
Failed to read images from Directory:  157
Exception Message:  index 52 is out of bounds for axis 0 with size 52
158
159
160
161
Failed to read images from Directory:  161
Exception Message:  index 52 is out of bounds for axis 0 with size 52
162
163
Failed to read images from Directory:  163
Exception Message:  index 52 is out of bounds for axis 0 with size 52
164
Failed to read images from Directory:  164
Exception Message:  index 52 is out of bounds for axis 0 with size 52
165
Failed to read images from Directory:  165
Exception Message:  index 52 is out of bounds for axis 0 with size 52
166
167
168
Failed to read images from Directory:  168
Exception Message:  index 52 is out of bounds for axis 0 with size 52
169
Failed to read images from Directory:  169
Exception Message:  index 52 is out of bounds for axis 0 with size 52
170
Failed to read images fr

277
278
Failed to read images from Directory:  278
Exception Message:  index 52 is out of bounds for axis 0 with size 52
279
Failed to read images from Directory:  279
Exception Message:  index 52 is out of bounds for axis 0 with size 52
280
Failed to read images from Directory:  280
Exception Message:  index 52 is out of bounds for axis 0 with size 52
281
Failed to read images from Directory:  281
Exception Message:  index 52 is out of bounds for axis 0 with size 52
282
Failed to read images from Directory:  282
Exception Message:  index 52 is out of bounds for axis 0 with size 52
283
284
Failed to read images from Directory:  284
Exception Message:  index 52 is out of bounds for axis 0 with size 52
285
Failed to read images from Directory:  285
Exception Message:  index 52 is out of bounds for axis 0 with size 52
286
Failed to read images from Directory:  286
Exception Message:  index 52 is out of bounds for axis 0 with size 52
287
Failed to read images from Directory:  287
Exception

Failed to read images from Directory:  404
Exception Message:  index 52 is out of bounds for axis 0 with size 52
405
Failed to read images from Directory:  405
Exception Message:  index 52 is out of bounds for axis 0 with size 52
406
Failed to read images from Directory:  406
Exception Message:  index 52 is out of bounds for axis 0 with size 52
407
Failed to read images from Directory:  407
Exception Message:  index 52 is out of bounds for axis 0 with size 52
408
409
Failed to read images from Directory:  409
Exception Message:  index 52 is out of bounds for axis 0 with size 52
410
411
Failed to read images from Directory:  411
Exception Message:  index 52 is out of bounds for axis 0 with size 52
412
413
Failed to read images from Directory:  413
Exception Message:  index 52 is out of bounds for axis 0 with size 52
414
415
416
417
418
419
Failed to read images from Directory:  419
Exception Message:  index 52 is out of bounds for axis 0 with size 52
420
421
Failed to read images from D

Failed to read images from Directory:  549
Exception Message:  index 52 is out of bounds for axis 0 with size 52
550
Failed to read images from Directory:  550
Exception Message:  index 52 is out of bounds for axis 0 with size 52
551
Failed to read images from Directory:  551
Exception Message:  index 52 is out of bounds for axis 0 with size 52
552
Failed to read images from Directory:  552
Exception Message:  index 52 is out of bounds for axis 0 with size 52
553
554
Failed to read images from Directory:  554
Exception Message:  index 52 is out of bounds for axis 0 with size 52
555
Failed to read images from Directory:  555
Exception Message:  index 52 is out of bounds for axis 0 with size 52
556
Failed to read images from Directory:  556
Exception Message:  index 52 is out of bounds for axis 0 with size 52
557
Failed to read images from Directory:  557
Exception Message:  index 52 is out of bounds for axis 0 with size 52
558
Failed to read images from Directory:  558
Exception Message

703
704
Failed to read images from Directory:  704
Exception Message:  index 52 is out of bounds for axis 0 with size 52
705
Failed to read images from Directory:  705
Exception Message:  index 52 is out of bounds for axis 0 with size 52
706
Failed to read images from Directory:  706
Exception Message:  index 52 is out of bounds for axis 0 with size 52
707
Failed to read images from Directory:  707
Exception Message:  index 52 is out of bounds for axis 0 with size 52
708
709
Failed to read images from Directory:  709
Exception Message:  index 52 is out of bounds for axis 0 with size 52
710
711
712
Failed to read images from Directory:  712
Exception Message:  index 52 is out of bounds for axis 0 with size 52
713
Failed to read images from Directory:  713
Exception Message:  index 52 is out of bounds for axis 0 with size 52
714
Failed to read images from Directory:  714
Exception Message:  index 52 is out of bounds for axis 0 with size 52
715
Failed to read images from Directory:  715
E

In [27]:
F2= np.array(F)

In [29]:
np.savetxt('F.txt',F2, fmt='%s')


In [32]:
np.save('Fn', F2)

In [44]:
import pickle

In [46]:
with open('F.pkl','wb') as f:
    pickle.dump(F2, f)

In [50]:
with open('F.pkl','rb') as f:
     F4 = pickle.load(f)
     print(x.shape)

(398,)


In [52]:
F4

array([array([[   0,  979,  563, ...,    0,    0,    0],
       [ 970,    0,  924, ...,    0,    0,    0],
       [ 639,  962,    0, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0, 1002, 1019],
       [   0,    0,    0, ...,  761,    0,  915],
       [   0,    0,    0, ...,  936, 1171,    0]]),
       array([[   0,  979,  563, ...,  186,    0,    0],
       [ 970,    0,  924, ...,  131,    0,    0],
       [ 639,  962,    0, ...,   89,    0,    0],
       ...,
       [ 117,   73,   67, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0, 1453],
       [   0,    0,    0, ...,    0, 1492,    0]]),
       array([[   0,  979,  563,  324,    0,    0,    0,    0,    0,    0,  114,
         167,  193,  144,  147,  125,    0],
       [ 970,    0,  924,  461,    0,    0,    0,    0,    0,    0,  100,
         104,  126,  117,  115,  148,    0],
       [ 639,  962,    0,  798,    0,    0,    0,    0,    0,    0,   37,
          74,   90,  229,  197,  162,  

In [49]:
np.array(X).shape

(49323, 224, 224, 3)

In [22]:
(np.array(F[2])).shape

(17, 17)

In [20]:
len(F)

398

In [23]:
F[2]

array([[   0,  979,  563,  324,    0,    0,    0,    0,    0,    0,  114,
         167,  193,  144,  147,  125,    0],
       [ 970,    0,  924,  461,    0,    0,    0,    0,    0,    0,  100,
         104,  126,  117,  115,  148,    0],
       [ 639,  962,    0,  798,    0,    0,    0,    0,    0,    0,   37,
          74,   90,  229,  197,  162,    0],
       [ 407,  496,  847,    0,    0,    0,   32,    0,    9,   31,   19,
          41,   18,   80,  130,  123,    0],
       [  11,    0,    0,    0,    0, 1240,  766,  221,   31,    0,   23,
          54,   36,   57,  129,   73,    8],
       [   0,    0,    1,    0, 1115,    0, 1272,  439,   82,   39,   48,
          82,   60,   62,   76,    0,   80],
       [   0,    0,   16,   12,  704, 1263,    0,  889,  230,  118,   62,
          46,   22,    0,    2,    0,  111],
       [   0,    0,    4,    0,  301,  492,  913,    0,  324,  128,    0,
           0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    2,  101,  137

In [39]:
len(temp)

42

In [32]:
(np.array(direcX)).shape

(8,)

In [35]:
(np.array(direcX[0])).shape

(52, 224, 224, 3)

In [31]:
np.array(temp).shape

(42, 224, 224, 3)

In [36]:
(np.array(direcX[0][0])).shape

(224, 224, 3)

In [ ]:
            img1 = cv2.imread("C:\\Users\\kuruparans\\Desktop\\tripletCar\\image_triplet_loss\\data\\01.jpg")
            img2 = cv2.imread("C:\\Users\\kuruparans\\Desktop\\tripletCar\\image_triplet_loss\\data\\02.jpg")

In [37]:
img1 = (np.array(direcX[0][0]))
img2 = (np.array(direcX[0][1]))

In [45]:

            
            orb = cv2.ORB_create(10000)
            orb.setFastThreshold(0)
            if cv2.__version__.startswith('3'):
                matcher = cv2.BFMatcher(cv2.NORM_HAMMING)
            else:
                matcher = cv2.BFMatcher_create(cv2.NORM_HAMMING)
            gms = GmsMatcher(orb, matcher)

            matches = gms.compute_matches(img1, img2)
            #gms.draw_matches(img1, img2, DrawingType.ONLY_LINES)
            #gms.draw_matches(img1, img2, DrawingType.LINES_AND_POINTS)
            print(len(matches))

Found 0 matches
0


In [49]:
y

['001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '001',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '002',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',
 '003',


In [50]:

feature = [[0 for i in range(len(temp))] for j in range(len(temp))] 

for i in range(0,len(temp)):
    for j in range(0,len(temp)):
        img1 = (np.array(direcX[0][i]))
        img2 = (np.array(direcX[0][j]))

        if(i==j):
            continue
        
        if(i!=j):
            orb = cv2.ORB_create(10000)
            orb.setFastThreshold(0)
            if cv2.__version__.startswith('3'):
                matcher = cv2.BFMatcher(cv2.NORM_HAMMING)
            else:
                matcher = cv2.BFMatcher_create(cv2.NORM_HAMMING)
            gms = GmsMatcher(orb, matcher)

            matches = gms.compute_matches(img1, img2)
            #gms.draw_matches(img1, img2, DrawingType.ONLY_LINES)
            #gms.draw_matches(img1, img2, DrawingType.LINES_AND_POINTS)
            #print(len(matches))           
            feature[i][j]=len(matches)
            

Found 979 matches
Found 563 matches
Found 324 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 114 matches
Found 167 matches
Found 193 matches
Found 144 matches
Found 147 matches
Found 125 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 214 matches
Found 260 matches
Found 222 matches
Found 222 matches
Found 275 matches
Found 162 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 221 matches
Found 180 matches
Found 970 matches
Found 924 matches
Found 461 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 100 matches
Found 104 matches
Found 126 matches
Found 117 matches
Found 115 matches
Found 148 matches
Found 0 matches
Found 0 matches
Found 0 matches
Foun

Found 0 matches
Found 435 matches
Found 478 matches
Found 125 matches
Found 142 matches
Found 98 matches
Found 30 matches
Found 29 matches
Found 23 matches
Found 30 matches
Found 0 matches
Found 7 matches
Found 0 matches
Found 1021 matches
Found 1252 matches
Found 1469 matches
Found 1219 matches
Found 1023 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 361 matches
Found 274 matches
Found 472 matches
Found 506 matches
Found 498 matches
Found 561 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 406 matches
Found 353 matches
Found 102 matches
Found 55 matches
Found 89 matches
Found 45 matches
Found 32 matches
Found 42 matches
Found 44 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 972 matches
Found 1240 matches
Found 1493 matches
Found 1438 matches
Found 122

Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 440 matches
Found 415 matches
Found 140 matches
Found 114 matches
Found 49 matches
Found 0 matches
Found 4 matches
Found 34 matches
Found 54 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 480 matches
Found 400 matches
Found 346 matches
Found 391 matches
Found 288 matches
Found 263 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 1033 matches
Found 1051 matches
Found 1194 matches
Found 1007 matches
Found 485 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 330 matches
Found 382 matches
Found 205 matches
Found 144 matches
Found 120 matches
Found 54 matches
Found 14 matches
Found 0 matches
Found 69 matches
Found 

Found 143 matches
Found 119 matches
Found 76 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 952 matches
Found 900 matches
Found 916 matches
Found 643 matches
Found 476 matches
Found 546 matches
Found 1444 matches
Found 1460 matches
Found 1208 matches
Found 1066 matches
Found 1084 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 21 matches
Found 15 matches
Found 0 matches
Found 82 matches
Found 30 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 35 matches
Found 0 matches
Found 366 matches
Found 271 matches
Found 266 matches
Found 216 matches
Found 168 matches
Found 59 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 0 matches
Found 3 matches
Found 0 matches
Found 955 matches
Found 1021 matches
Found 1118 matches
Found 793 matches
Found 711 matches
Found 635 matches
Found 986 matches
Found 1384 matches
Found

In [55]:
np.squeeze(np.asarray(feature))

array([[  0, 979, 563, ...,   0, 221, 180],
       [970,   0, 924, ...,   0, 137, 113],
       [639, 962,   0, ...,   0,  71,  65],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [101,  32,  29, ...,   0,   0, 955],
       [103,  62,  60, ...,   0, 941,   0]])

In [52]:
np.array(feature).shape

(42, 42)

In [19]:
model = TripletLoss()


In [5]:
placeholder_shape = [None]

In [6]:

placeholder_shape = [None] + list(dataset.images_train.shape[1:])
print("placeholder_shape", placeholder_shape)


placeholder_shape [None, 224, 224, 3]


In [7]:
next_batch = dataset.get_triplets_batch


In [20]:

# Setup Network
anchor_input = tf.placeholder(tf.float32, placeholder_shape, name='anchor_input')
positive_input = tf.placeholder(tf.float32, placeholder_shape, name='positive_input')
negative_input = tf.placeholder(tf.float32, placeholder_shape, name='negative_input')

margin = 0.5
anchor_output = model.conv_net2(anchor_input, reuse=False)
positive_output = model.conv_net2(positive_input, reuse=True)
negative_output = model.conv_net2(negative_input, reuse=True)
loss = model.triplet_loss(anchor_output, positive_output, negative_output, margin)

# Setup Optimizer
global_step = tf.Variable(0, trainable=False)

train_step = tf.train.MomentumOptimizer(0.01, 0.99, use_nesterov=True).minimize(loss, global_step=global_step)


AttributeError: 'Activation' object has no attribute 'outbound_nodes'

In [6]:
anchor_input

<tf.Tensor 'anchor_input:0' shape=(?, 122, 122, 3) dtype=float32>

In [7]:
anchor_output

<tf.Tensor 'model/Flatten/flatten/Reshape:0' shape=(?, 448) dtype=float32>

In [8]:
from preprocessing import PreProcessing
from model import TripletLoss
next_batch = dataset.get_triplets_batch


In [9]:
# Start Training
saver = tf.train.Saver()
with tf.device('/gpu:1'):

    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:
        sess.run(tf.global_variables_initializer())

        # Setup Tensorboard
        tf.summary.scalar('step', global_step)
        tf.summary.scalar('loss', loss)
        for var in tf.trainable_variables():
            tf.summary.histogram(var.op.name, var)
        merged = tf.summary.merge_all()
        writer = tf.summary.FileWriter('train.log', sess.graph)

        # Train iter
        for i in range(1):
            batch_anchor, batch_positive, batch_negative = next_batch(2)
           # print(batch_anchor)
            
            _, l, summary_str = sess.run([train_step, loss, merged],
                                         feed_dict={anchor_input: batch_anchor, positive_input: batch_positive, negative_input: batch_negative})

            writer.add_summary(summary_str, i)
            print("\r#%d - Loss" % i, l)

            if (i + 1) % FLAGS.step == 0:
                saver.save(sess, "model_triplet/model128.ckpt")
        saver.save(sess, "model_triplet/model128.ckpt")
print('Training completed successfully.')


(333, 122, 122, 3)
(122, 122, 3) (122, 122, 3)


error: OpenCV(4.2.0) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<1,-1,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)


In [ ]:
batch_anchor.shape